version: "3.0"

services:

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${JSWM_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${JSWM_MYSQL_DATABASE}
      - MYSQL_USER=${JSWM_MYSQL_USER}
      - MYSQL_PASSWORD=${JSWM_MYSQL_PASSWORD}
    restart: unless-stopped
    volumes:
      - vdb:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_bin

  jira:
    build:
      context: ./jira
    environment:
      - VIRTUAL_HOST=${JSWM_VIRTUAL_HOST}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${JSWM_LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=sovanna.hing@gmail.com
    restart: unless-stopped
    expose:
      - 8080
    depends_on:
      - mysql
    volumes:
      - vjira:/var/lib/atlassian/jira
      - vjirainstall:/opt/atlassian/jira

networks:
  default:
    external:
       name: nginx-proxy

volumes:
  vdb:
  vjira:
  vjirainstall:
